### ISSUE TITLE
Кодовая синхронизация репозиториев skypeopensource2 с skypeopensource2_dev

### ISSUE THREAD

**Issue by AntonBoch1244** [skypeopensource/skypeopensource2#11]
Я предлагаю закрыть репозиторий skypeopensource2_dev и создать ветку dev и сделать её главной в этом репозитории так как англоязычные пользователи заливают свой код в этот репозиторий и им попросту не нужен другой репозиторий.
А синхронизацию веток проводить методом который указан в git wiki.

В случае принятия данного решения:
 1. Ваш код будет сохранен.
 1. Стабильный код не будет затронут до того момента когда ветка dev мержнется.
 1. Уберётся рутина с перемещением файлов из 1 репозитория в другой на вашей машине.
 1. У контрибюторов будет возможность писать код где надо, а не где попало.

В случае отказа от данного решения:
 1. Ваш код будет сохранен.
 1. Стабильный код не будет затронут до того момента когда файлы на вашей машине отправятся в master.
 1. Останется рутина с перемещением файлов из 1 репозитория в другой на вашей машине.
 1. Контрибюторы будут не понимать куда вообще всё это кидается(Вне зависимости от существования CONTRIBUTING.md).

**Comment by Randl** [comment]
Полностью поддерживаю

**Comment by AntonBoch1244** [comment]
Я наверное продублирую это в skypeopensource2_dev.

**Comment by skypeopensource** [comment]
No.

**Comment by AntonBoch1244** [comment]
Если ответ нет тогда посмотрите REF.
