### ISSUE TITLE
Not first

### ISSUE THREAD

**Issue by emersion** [skypeopensource/skypeopensource2#4]
See https://github.com/Delthas/JavaSkype

**Comment by skypeopensource** [comment]
They use MSNP24 proto. Its not original skype proto used in skype5.5 and skype6.x versions (before MS buy Skype).

**Comment by emersion** [comment]
Okay. But this old proto is deprecated now, right?

**Comment by skypeopensource** [comment]
@emersion 

I don't know. Formally, maybe yes. But it still heavy used for audio/video for example (but not sure, because don't see in it yet).
