### ISSUE TITLE
Spasibo za kommenty, bro

### ISSUE THREAD

**Issue by feb21** [skypeopensource/skypeopensource2#7]
chesno govorya lublyu vas za kommenty v kode:)

**Comment by skypeopensource** [comment]
Spasibo :)

Kakie imenno? Mne samomu interesno chto ludyam ponravilos :)

**Comment by TiberiumPY** [comment]
Ya tak i znal, chto tolko russkie mogut reversit' client skaipa :+1:

**Comment by skypeopensource** [comment]
@TiberiumPY 

Efim Bushmanov its russian name and lastname :)
Some info, if you like.

An exclusive interview with Skype reverse engineer Efim Bushmanov 
http://www.ewdn.com/2011/06/05/ewdn-exclusive-an-interview-with-efim-bushmanov/

**Comment by TiberiumPY** [comment]
@skypeopensource eto it shtoli? ya chital ety novost'

**Comment by skypeopensource** [comment]
@TiberiumPY 

Ya.

**Comment by TiberiumPY** [comment]
@skypeopensource yobana vrot... ipat. Dak togda tebya chut' ne posadili?

**Comment by skypeopensource** [comment]
@TiberiumPY 

Kogda? I za chto?

**Comment by brainblowjob** [comment]
@skypeopensource prosto iz za license u vseh gorit

**Comment by aolko** [comment]
Ребят, чё за херня, юникод же работает

**Comment by TiberiumPY** [comment]
@aolko na githabe nado english letters ispolzovat!!!! russkie bukvi nekosherno

**Comment by brainblowjob** [comment]
@aolko nu i dlya togo chtobi ne palitsa pered dyadyami, kotorie nikogda ne pojmut etot velikij yazyk

**Comment by aolko** [comment]
Это пиздиотизм

**Comment by TiberiumPY** [comment]
@aolko ti pro sebya ? :)

**Comment by aolko** [comment]
я про ебанутые латинские комменты

**Comment by TiberiumPY** [comment]
@aolko nam poxuy, idi naxuy s github'a esli ti takoi dayn

**Comment by aolko** [comment]
@TiberiumPY бомбануло :)

**Comment by TiberiumPY** [comment]
@aolko ne, mne poxyu

**Comment by TiberiumPY** [comment]
@aolko vse privikli na github na english razgovarivat'

**Comment by aolko** [comment]
@TiberiumPY транслит не английский, алё, совсем уже отличать языки разучился?

**Comment by brainblowjob** [comment]
@aolko tebe che po usham nastuchatq, snob ebanii?

**Comment by AntonBoch1244** [comment]
@brainblowjob Прошу вас не выражаться на транслите, да и вообще предлагаю закрыть этот issue, так как он не помогает проекту.

**Comment by brainblowjob** [comment]
@AntonBoch1244 ya dymal takie dauni vymerli 

![](http://image.prntscr.com/image/349c3f1c395142d296216abbe6427664.png)

**Comment by AntonBoch1244** [comment]
@brainblowjob Самостоятельное продвижение своего же поста в GitHub никто не запрещает!

**Comment by brainblowjob** [comment]
@AntonBoch1244 как и быть дерьмом

**Comment by aolko** [comment]
@AntonBoch1244 пришёл ущемлять свободу слова? ;) сижу на год больше чем ты _фить ха_

**Comment by AntonBoch1244** [comment]
@brainblowjob мне если честно по-барабану ваше мнение, я вижу что вы пытаетесь меня затроллить, но боюсь вы не как не измените моё мнение касательно этого issue.
@aolko я здесь не ради ущемления свободы слова и прошу прощения за заданный мною вам второй вопрос.

**Comment by aolko** [comment]
@AntonBoch1244 го репортить мудаков

**Comment by AntonBoch1244** [comment]
@aolko это бесполезно.

**Comment by aolko** [comment]
@AntonBoch1244 мне уже отписали с ТП гитхаба

**Comment by bugaevc** [comment]
@skypeopensource this is getting ridiculous. Please close or delete this issue.

**Comment by feb21** [comment]
bugaevc pidor i zanuda

**Comment by TiberiumPY** [comment]
@feb21 plus plus plus blin
